from collections.abc import Sequence
from typing import TypeAlias

import numpy as np
import numpy.typing as npt

Float32Array: TypeAlias = npt.NDArray[np.float32]
Float64Array: TypeAlias = npt.NDArray[np.float64]

class DwtPlanF32:
    def __init__(
        self,
        length: int,
        wavelet: str = "db1",
        mode: str = "symmetric",
    ) -> None: ...
    @property
    def signal_len(self) -> int: ...
    @property
    def coeff_len(self) -> int: ...
    @property
    def wavelet(self) -> str: ...
    @property
    def mode(self) -> str: ...
    @property
    def dtype(self) -> str: ...
    def forward(self, signal: Float32Array) -> tuple[Float32Array, Float32Array]: ...
    def inverse(
        self,
        approx: Float32Array,
        detail: Float32Array,
    ) -> Float32Array: ...

class DwtPlanF64:
    def __init__(
        self,
        length: int,
        wavelet: str = "db1",
        mode: str = "symmetric",
    ) -> None: ...
    @property
    def signal_len(self) -> int: ...
    @property
    def coeff_len(self) -> int: ...
    @property
    def wavelet(self) -> str: ...
    @property
    def mode(self) -> str: ...
    @property
    def dtype(self) -> str: ...
    def forward(self, signal: Float64Array) -> tuple[Float64Array, Float64Array]: ...
    def inverse(
        self,
        approx: Float64Array,
        detail: Float64Array,
    ) -> Float64Array: ...

class WavedecPlanF32:
    def __init__(
        self,
        length: int,
        wavelet: str = "db1",
        mode: str = "symmetric",
        level: int | None = None,
    ) -> None: ...
    @property
    def signal_len(self) -> int: ...
    @property
    def levels(self) -> int: ...
    @property
    def wavelet(self) -> str: ...
    @property
    def mode(self) -> str: ...
    @property
    def dtype(self) -> str: ...
    def forward(self, signal: Float32Array) -> list[Float32Array]: ...
    def inverse(self, bands: Sequence[Float32Array]) -> Float32Array: ...

class WavedecPlanF64:
    def __init__(
        self,
        length: int,
        wavelet: str = "db1",
        mode: str = "symmetric",
        level: int | None = None,
    ) -> None: ...
    @property
    def signal_len(self) -> int: ...
    @property
    def levels(self) -> int: ...
    @property
    def wavelet(self) -> str: ...
    @property
    def mode(self) -> str: ...
    @property
    def dtype(self) -> str: ...
    def forward(self, signal: Float64Array) -> list[Float64Array]: ...
    def inverse(self, bands: Sequence[Float64Array]) -> Float64Array: ...
