#!/usr/bin/env python3
"""Author exact binary64 built-in coefficients by spectral factorization."""

from __future__ import annotations

import argparse
import math
from pathlib import Path
import struct

import mpmath as mp


OUTPUT = Path("src/coefficients.rs")


def rust_bits(value: mp.mpf) -> str:
    bits = struct.unpack("!Q", struct.pack("!d", float(value)))[0]
    groups = f"{bits:016x}"
    return "0x" + "_".join(groups[index : index + 4] for index in range(0, 16, 4))


def render_array(name: str, values: list[mp.mpf]) -> list[str]:
    lines = [f"pub(crate) const {name}: [f64; {len(values)}] = ["]
    lines.extend(f"    f64::from_bits({rust_bits(value)})," for value in values)
    lines.append("];")
    return lines


def convolve(left: list[mp.mpc], right: list[mp.mpc]) -> list[mp.mpc]:
    result = [mp.mpc(0)] * (len(left) + len(right) - 1)
    for left_index, left_value in enumerate(left):
        for right_index, right_value in enumerate(right):
            result[left_index + right_index] += left_value * right_value
    return result


def daubechies(order: int) -> list[mp.mpf]:
    """Return the extremal-phase low-pass filter in PyWavelets order."""
    if order == 1:
        return [1 / mp.sqrt(2)] * 2

    # Daubechies' auxiliary polynomial:
    # P_N(y) = sum(k=0..N-1) binomial(N-1+k, k) y^k.
    auxiliary_ascending = [
        mp.mpf(math.comb(order - 1 + index, index)) for index in range(order)
    ]
    roots_y = mp.polyroots(
        list(reversed(auxiliary_ascending)),
        maxsteps=1000,
        error=False,
        extraprec=100,
    )

    # y = -(1-z)^2/(4z) gives reciprocal z-root pairs. Selecting the root
    # inside the unit circle produces the extremal-phase spectral factor.
    roots_z = []
    for root_y in roots_y:
        linear = 4 * root_y - 2
        discriminant = mp.sqrt(linear * linear - 4)
        candidates = [(-linear + discriminant) / 2, (-linear - discriminant) / 2]
        roots_z.append(min(candidates, key=abs))

    coefficients = [mp.mpc(1)]
    for _ in range(order):
        coefficients = convolve(coefficients, [mp.mpc(1), mp.mpc(1)])
    for root_z in roots_z:
        coefficients = convolve(coefficients, [-root_z, mp.mpc(1)])

    maximum_imaginary = max(abs(mp.im(value)) for value in coefficients)
    if maximum_imaginary > mp.mpf("1e-70"):
        raise ArithmeticError(
            f"db{order} spectral factor retained imaginary residue "
            f"{maximum_imaginary}"
        )
    real_coefficients = [mp.re(value) for value in coefficients]
    scale = mp.sqrt(2) / mp.fsum(real_coefficients)
    return [value * scale for value in real_coefficients]


def render() -> str:
    mp.mp.dps = 100
    filters = {order: daubechies(order) for order in range(1, 39)}

    lines = [
        "// @generated by tools/generate_builtin_coefficients.py; do not edit by hand.",
        "",
    ]
    for order, coefficients in filters.items():
        lines.extend(render_array(f"DB{order}_DEC_LO", coefficients))
        lines.append("")
    lines.extend(
        [
            "pub(crate) fn daubechies(order: usize) -> Option<&'static [f64]> {",
            "    match order {",
            *(f"        {order} => Some(&DB{order}_DEC_LO)," for order in filters),
            "        _ => None,",
            "    }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the checked-in Rust source is not reproducible",
    )
    args = parser.parse_args()
    generated = render()
    if args.check:
        if OUTPUT.read_text() != generated:
            raise SystemExit(f"{OUTPUT} is stale; regenerate it with {__file__}")
    else:
        OUTPUT.write_text(generated)


if __name__ == "__main__":
    main()
