// @generated by tools/generate_lattice_coefficients.py; do not edit by hand.

use crate::coefficients;

#[derive(Clone, Copy, Debug)]
pub(crate) struct LatticeSection {
    pub(crate) q: f64,
    pub(crate) chart: u8,
    pub(crate) determinant: i8,
}

#[derive(Debug)]
pub(crate) struct LatticeFactors {
    pub(crate) sections: &'static [LatticeSection],
    pub(crate) scale: f64,
}

const DB20_SECTIONS: [LatticeSection; 20] = [
    LatticeSection {
        q: f64::from_bits(0xbfb2_ed4e_36a9_04be),
        chart: 0,
        determinant: -1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfcc_c9a4_2f06_6562),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fd8_aee7_c2de_a1d0),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfe2_110b_68c1_6116),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fe8_beaa_9df6_2a1f),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfef_13f9_3c19_040b),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fe7_77f3_3572_fcf5),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfe1_8147_1a88_c05c),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fd9_57b2_3b66_56fa),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfd1_7393_500a_6136),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fc6_556d_ee78_78e6),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfb9_da4c_77d6_8540),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3faa_4b58_9355_21a0),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbf96_cfd2_9144_03ef),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3f80_6058_a127_3ecd),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbf62_ceb9_1d6f_f0ab),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3f40_89fb_24b6_071e),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbf14_dc11_cf67_664c),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3ee0_c560_86c3_2c5b),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3e99_cd78_ddaa_157c),
        chart: 1,
        determinant: 1,
    },
];
const DB20: LatticeFactors = LatticeFactors {
    sections: &DB20_SECTIONS,
    scale: f64::from_bits(0x3fd1_d43f_d5d3_4007),
};

const SYM20_SECTIONS: [LatticeSection; 20] = [
    LatticeSection {
        q: f64::from_bits(0xbfe0_7741_e506_aa92),
        chart: 1,
        determinant: -1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fdc_8212_2acd_24ae),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfc9_dc78_3f5e_9214),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfb8_2981_a301_f42e),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfc4_8936_a614_b31a),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfbf_6be7_124d_b5fd),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fee_e2a3_c231_f41d),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfe4_95d2_bdf4_bc8d),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fdd_55ba_919a_b826),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfb1_05b2_62c7_f49d),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfd0_0477_7585_a855),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fde_a00a_1cbf_cc1e),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfec_be63_1c91_4a9d),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fe7_15ab_e9bb_4b56),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfb0_00e0_eabb_52d4),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfd4_e50d_2033_a6ed),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfd9_5ad3_c4e3_4812),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fdb_cf72_6178_5a2a),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fec_1646_7fcf_158c),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fe2_af41_79d4_4126),
        chart: 1,
        determinant: 1,
    },
];
const SYM20: LatticeFactors = LatticeFactors {
    sections: &SYM20_SECTIONS,
    scale: f64::from_bits(0x3fbe_41f9_3da9_8eb6),
};

const DB38_SECTIONS: [LatticeSection; 38] = [
    LatticeSection {
        q: f64::from_bits(0xbfa4_6990_ced1_b871),
        chart: 0,
        determinant: -1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfbe_beaa_88e2_603c),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fc9_d585_54b0_2548),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfd2_5036_7ad1_8cdb),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fd7_f3e0_68c5_3931),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfdd_ecdd_cfd9_cb6d),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fe2_2b87_b8ac_8812),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfe5_aa94_a4f4_c697),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fe9_89d1_1d7d_58de),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfed_e681_fb34_293d),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fed_55c3_5902_5b41),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfe9_1d5f_c874_10a1),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fe5_6bc2_45d9_e858),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfe2_23ec_bc66_ca40),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fde_6421_3d73_e963),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfd9_1269_a8b7_00d8),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fd4_43c2_8cb0_097e),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfcf_e537_ea6b_940b),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fc8_427b_b4c3_0c4d),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfc1_aec2_69b6_8fa3),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fb8_78ae_729a_df53),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfaf_d5b1_d952_ad53),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fa3_4636_3e0f_0283),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbf95_85bd_7ec9_271b),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3f85_f87b_5c25_39f1),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbf74_5675_300e_5f91),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3f60_efd6_7518_2590),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbf49_2c0d_b8c7_e331),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3f30_8b12_1a33_6f96),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbf13_08a3_4903_53e4),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3ef2_eebc_e45f_a5e6),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbed0_078b_874d_0e4a),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3ea6_a3a4_578e_9208),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbe79_f02c_607f_d028),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3e47_2740_41bf_13ed),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbe0e_34a1_ab8c_a5b1),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3dc9_9bda_8cc7_d54f),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3d75_2ccf_3a40_29f4),
        chart: 1,
        determinant: 1,
    },
];
const DB38: LatticeFactors = LatticeFactors {
    sections: &DB38_SECTIONS,
    scale: f64::from_bits(0xbfba_4f66_beeb_dd54),
};

const COIF17_SECTIONS: [LatticeSection; 51] = [
    LatticeSection {
        q: f64::from_bits(0x3fe9_6202_e7c4_d272),
        chart: 0,
        determinant: -1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fd1_a07c_ea54_fdbf),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfd4_2ea7_dd52_8794),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fd4_ccf4_9be8_edbc),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfd9_140e_5790_c7bb),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fe2_5b31_fee3_292c),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfec_205e_ba3b_287e),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fee_0695_ba48_7db5),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfef_f759_18b7_2720),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3feb_88af_a20f_907b),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfe2_49b6_c630_2979),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fe0_c2bc_7d11_9096),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfdd_440d_e5c1_53c3),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fd2_2877_0def_47b6),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfcf_6955_3611_1a53),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fbf_caaf_fa7d_01f2),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfa7_b1d7_ed10_0f96),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfa4_5045_3c18_afc5),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fc1_2c3c_73d5_c220),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfc8_ae68_58df_863e),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fd5_777d_8b4a_c3f9),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfd6_c982_ec58_0fde),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fe0_0189_6595_b5d9),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfe5_135e_ba36_8b44),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fe4_1e10_3899_84da),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfea_36b1_e5ba_3ade),
        chart: 1,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3feb_639e_6122_5d93),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfea_c66e_193d_c92d),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fec_dbd9_b52d_bb13),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfe7_fe1f_9265_2d8e),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fdf_e073_98ab_9095),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfd5_0d33_769d_85cb),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3fd0_edf8_df59_67d0),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbf7b_75b6_0ad5_cc98),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfb1_209f_1bcb_764f),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfb7_2e30_1f50_e589),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3faf_0293_419b_ffe8),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbfa1_9450_8456_bfbd),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3f92_0d5c_324b_d37d),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbf80_c4c4_6eca_e93f),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3f6b_ea45_6f27_aadc),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbf54_9860_cf1a_2210),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3f3a_9e82_5d25_002f),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbf1d_bb9e_5fa8_2f76),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3efc_3cc9_faea_6c8e),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbed6_551d_6eff_4b3f),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3eac_9a49_77a1_148d),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbe7c_7bb3_1153_98d0),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0x3e44_aedc_8d1f_f65d),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbe03_7a77_e763_4c5b),
        chart: 0,
        determinant: 1,
    },
    LatticeSection {
        q: f64::from_bits(0xbdb1_d9ff_93be_ed77),
        chart: 1,
        determinant: 1,
    },
];
const COIF17: LatticeFactors = LatticeFactors {
    sections: &COIF17_SECTIONS,
    scale: f64::from_bits(0x3f89_d6ae_8fc7_49fa),
};

pub(crate) fn analysis(dec_lo: &[f64]) -> Option<&'static LatticeFactors> {
    match dec_lo.len() {
        40 if dec_lo == coefficients::DB20_DEC_LO => Some(&DB20),
        40 if dec_lo == coefficients::SYM20_DEC_LO => Some(&SYM20),
        76 if dec_lo == coefficients::DB38_DEC_LO => Some(&DB38),
        102 if dec_lo == coefficients::COIF17_DEC_LO => Some(&COIF17),
        _ => None,
    }
}
